-- ============================================================================
--  皮肤商城 · 数据库补丁（移植自上游 skin-shop-schema.sql / skin-equip.sql）
--  ---------------------------------------------------------------------------
--  适配说明：上游的 SQL 直接面向作者老库（users.id 为 uuid）；本仓库
--  db/schema.core.sql 定义的新库 users.id 为 bigint，因此外键列类型
--  与 users.id 自动对齐（沿用 compat.sql 的动态探测写法），两库都能跑。
--  执行：由 scripts/apply-schema.mjs 追加
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. users 新增字段
-- ---------------------------------------------------------------------------
do $blk$
begin
    if not exists (select 1 from information_schema.columns
                   where table_schema='public' and table_name='users' and column_name='coins') then
        alter table public.users add column coins int not null default 0;
    end if;
    if not exists (select 1 from information_schema.columns
                   where table_schema='public' and table_name='users' and column_name='bubble_skin') then
        alter table public.users add column bubble_skin int not null default 0;
    end if;
end
$blk$;

-- ---------------------------------------------------------------------------
-- 2. 皮肤价格配置（管理员可改）
-- ---------------------------------------------------------------------------
create table if not exists public.skin_prices (
    skin_id       int primary key,
    price         int not null default 100,
    duration_days int not null default 30,
    updated_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3. 购买记录（user_id 类型与 users.id 对齐）
-- ---------------------------------------------------------------------------
do $blk$
declare
    uid_type text;
begin
    select format_type(a.atttypid, a.atttypmod) into uid_type
      from pg_attribute a join pg_class c on c.oid=a.attrelid
      join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relname='users' and a.attname='id'
       and a.attnum>0 and not a.attisdropped;

    if to_regclass('public.skin_purchases') is null then
        execute format(
            'create table public.skin_purchases (
                 id bigint generated by default as identity primary key,
                 user_id %1$s not null references public.users (id) on delete cascade,
                 skin_id  int not null,
                 price    int not null,
                 expire_at timestamptz not null,
                 created_at timestamptz not null default now())', uid_type);
    end if;

    if to_regclass('public.coin_transactions') is null then
        execute format(
            'create table public.coin_transactions (
                 id bigint generated by default as identity primary key,
                 user_id %1$s not null references public.users (id) on delete cascade,
                 amount  int not null,
                 reason  text,
                 created_at timestamptz not null default now())', uid_type);
    end if;

    if to_regclass('public.bubble_gift_claims') is null then
        execute format(
            'create table public.bubble_gift_claims (
                 id bigint generated by default as identity primary key,
                 user_id %1$s not null references public.users (id) on delete cascade,
                 day     date not null default current_date,
                 created_at timestamptz not null default now())', uid_type);
    end if;
end
$blk$;

-- ---------------------------------------------------------------------------
-- 4. 商店活动
-- ---------------------------------------------------------------------------
create table if not exists public.shop_activities (
    id          bigint generated by default as identity primary key,
    title       text not null,
    description text,
    discount    int not null default 0,
    start_at    timestamptz,
    end_at      timestamptz,
    active      boolean not null default true,
    created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 5. 初始化 45 套皮肤价格（1..44 各 100 币 / 30 天，0 号原版免费不参与）
-- ---------------------------------------------------------------------------
insert into public.skin_prices (skin_id, price, duration_days)
select g, 100, 30 from generate_series(1, 44) as g
on conflict (skin_id) do nothing;

-- ---------------------------------------------------------------------------
-- 6. 索引
-- ---------------------------------------------------------------------------
do $blk$
begin
    if exists (select 1 from information_schema.tables where table_schema='public' and table_name='skin_purchases') then
        create index if not exists idx_skin_purchases_user on public.skin_purchases(user_id);
        create index if not exists idx_skin_purchases_expire on public.skin_purchases(expire_at);
    end if;
    if exists (select 1 from information_schema.tables where table_schema='public' and table_name='coin_transactions') then
        create index if not exists idx_coin_tx_user on public.coin_transactions(user_id);
    end if;
    if exists (select 1 from information_schema.tables where table_schema='public' and table_name='bubble_gift_claims') then
        create unique index if not exists idx_bubble_gift_unique on public.bubble_gift_claims(user_id, day);
    end if;
end
$blk$;

-- ---------------------------------------------------------------------------
-- 7. RLS：商城表对 anon 开放读写（与全站 A 档策略一致）
-- ---------------------------------------------------------------------------
do $$
declare
    t text;
    tbls text[] := array['skin_prices','skin_purchases','shop_activities','coin_transactions','bubble_gift_claims'];
    pol_count int;
begin
    foreach t in array tbls loop
        if exists (select 1 from information_schema.tables where table_schema='public' and table_name=t) then
            select count(*) into pol_count from pg_policies where schemaname='public' and tablename=t;
            if pol_count = 0 then
                execute format('alter table public.%I disable row level security', t);
            end if;
            execute format('alter publication supabase_realtime add table public.%I', t);
        end if;
    end loop;
exception when others then
    raise notice 'realtime 发布跳过（无 supabase_realtime）: %', sqlerrm;
end $$;
